# Generated by Django 3.2.6 on 2021-10-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date_time',
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
